### ISSUE TITLE
new Jenkins ( 2.346.2 ) & Maven ( 3.8.4 ) versions  

### ISSUE THREAD

**Issue by abduallahii** [anshulc55/Jenkins_Upgradev3#61]
you might need to upgrade pom.xml   with new maven-compiler-plugin version as below 

        <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
--------------- ERROR --------------------
[logs.txt](https://github.com/anshulc55/Jenkins_Upgradev3/files/9291621/logs.txt)

**Comment by anshulc55** [comment]
This is done, version upgarded.
